SCALEMAP = {
        "major pentatonic": "I II III V VI",
        "minor pentatonic": "I bIII IV V bVII",
        "major blues":      "I II bIII III V VI",
        "minor blues":      "I bIII IV bV V bVII",
        "lydian":           "I II III #IV V VI VII",
        "lydian dominant":  "I II III #IV V VI bVII",
        "lydian augmented": "I II III #IV #V VI VII",
        "ionian":           "I II III IV V VI VII",
        "harmonic major":   "I II III IV V bVI VII",
        "melodic major":    "I II III IV V bVI bVII",
        "mixolydian":       "I II III IV V VI bVII",
        "dorian":           "I II bIII IV V VI bVII",
        "aeolian":          "I II bIII IV V bVI bVII",
        "melodic minor":    "I II bIII IV V VI VII",
        "harmonic minor":   "I II bIII IV V bVI VII",
        "phrygian":         "I bII bIII IV V bVI bVII",
        "altered phrygian": "I bII III IV V bVI VII",
        "locrian":          "I bII bIII IV bV bVI bVII",
        "super locrian":    "I bII bIII bIV bV bVI bVII",
        "altered dominant": "I bII bIII bIV bV bVI bVII",
        "whole tone":       "I II III #IV bVI bVII",
        "diminished":       "I II bIII IV bV bVI bbVII VII"
}
