SCALELIST = [
        "major pentatonic",
        "minor pentatonic",
        "major blues",
        "minor blues",
        "lydian",
        "lydian dominant",
        "lydian augmented",
        "ionian",
        "harmonic major",
        "melodic major",
        "mixolydian",
        "dorian",
        "aeolian",
        "melodic minor",
        "harmonic minor",
        "phrygian",
        "altered phrygian",
        "locrian",
        "super locrian",
        "altered dominant",
        "whole tone",
        "diminished"
]
